Repository lucas0headshot/GS-SENAC_backend, pull requests merged in 2024-07, with the labels that each got.

#30 raw: gestao_cursos.json
  backend/insomnia/gestao_cursos.json
Labels: enhancement

#35 docs: feature-request templates
  .github/ISSUE_TEMPLATE/sugerir-funcionalidade.md
Labels: documentation

#34 docs: issues templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/reportar-bug.md
Labels: documentation

#31 feat: FrequenciaDTO
  backend/src/main/java/com/senac/gestaocurso/dto/FrequenciaDto.java
  backend/src/main/java/com/senac/gestaocurso/resource/FrequenciaController.java
  backend/src/main/java/com/senac/gestaocurso/service/FrequenciaService.java
Labels: enhancement

#36 remove: feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: duplicate

#33 feat: implementar RNs
  backend/src/main/java/com/senac/gestaocurso/models/Chamada.java
  backend/src/main/java/com/senac/gestaocurso/models/DadosBancario.java
  backend/src/main/java/com/senac/gestaocurso/models/Dependente.java
  backend/src/main/java/com/senac/gestaocurso/models/ExperienciaAnterior.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Certificacao.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Curso.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Frequencia.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Inscricao.java
  backend/src/main/java/com/senac/gestaocurso/repository/InscricaoRepository.java
  backend/src/main/java/com/senac/gestaocurso/service/AulaService.java
  backend/src/main/java/com/senac/gestaocurso/service/InscricaoService.java
  backend/src/main/java/com/senac/gestaocurso/strategy/NovaValidacaoInscricaoStrategy.java
  backend/src/main/java/com/senac/gestaocurso/strategy/aulaValidacaoImp/ValidarDiaAnteriorADiaDaAula.java
  backend/src/main/java/com/senac/gestaocurso/strategy/inscricao/ValidarFuncionario.java
  backend/src/main/java/com/senac/gestaocurso/strategy/inscricao/ValidarQuantidaInscricao.java
Labels: enhancement

#32 feat: Builder
  backend/src/main/java/com/senac/gestaocurso/dto/AulaDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/CertificaoDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/CursoDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/FrequenciaDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/InscricaoDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/MateriaDto.java
  backend/src/main/java/com/senac/gestaocurso/models/Cargo.java
  backend/src/main/java/com/senac/gestaocurso/models/Certificacao.java
  backend/src/main/java/com/senac/gestaocurso/models/Chamada.java
  backend/src/main/java/com/senac/gestaocurso/models/DadosBancario.java
  backend/src/main/java/com/senac/gestaocurso/models/Dependente.java
  backend/src/main/java/com/senac/gestaocurso/models/ExperienciaAnterior.java
  backend/src/main/java/com/senac/gestaocurso/models/Funcionario.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Aula.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Curso.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Frequencia.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Inscricao.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Materia.java
  backend/src/main/java/com/senac/gestaocurso/repository/CertifcacaoRepository.java
  backend/src/main/java/com/senac/gestaocurso/repository/ChamadaRepository.java
  backend/src/main/java/com/senac/gestaocurso/resource/CertificacaoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/ChamadaController.java
  backend/src/main/java/com/senac/gestaocurso/service/AulaService.java
  backend/src/main/java/com/senac/gestaocurso/service/CertificacaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/ChamadaService.java
  backend/src/main/java/com/senac/gestaocurso/service/CursoService.java
  backend/src/main/java/com/senac/gestaocurso/service/InscricaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/MateriaService.java
  backend/src/main/java/com/senac/gestaocurso/strategy/funcionarioValidacaoImp/ImplementaListaCertificacao.java
  backend/src/main/resources/application.properties
Labels: enhancement

#37 docs: README
  README.md
Labels: documentation

#38 feat: cors config
  backend/src/main/java/com/senac/gestaocurso/CorsConfig.java
Labels: bug

#40 fix: Builders
  backend/src/main/java/com/senac/gestaocurso/dto/InscricaoDto.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Inscricao.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Materia.java
  backend/src/main/java/com/senac/gestaocurso/service/InscricaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/MateriaService.java
Labels: bug

#39 raw: seeder.sql
  database/seeder.sql
Labels: enhancement

#41 fix: remoção da assinatura CascadeType.ALL
  backend/src/main/java/com/senac/gestaocurso/models/Funcionario.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Aula.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Curso.java
Labels: bug

#42 refact: colocando a paginação para padrão 10
  backend/src/main/java/com/senac/gestaocurso/resource/AulaController.java
  backend/src/main/java/com/senac/gestaocurso/resource/CargoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/CertificacaoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/CursoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/DadosBancarioController.java
  backend/src/main/java/com/senac/gestaocurso/resource/DependenteController.java
  backend/src/main/java/com/senac/gestaocurso/resource/ExperienciaAnteriorController.java
  backend/src/main/java/com/senac/gestaocurso/resource/FiliacaoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/FrequenciaController.java
  backend/src/main/java/com/senac/gestaocurso/resource/FuncionarioController.java
  backend/src/main/java/com/senac/gestaocurso/resource/InscricaoController.java
  backend/src/main/java/com/senac/gestaocurso/resource/MateriaController.java
Labels: refactor

#43 fix: corrigindo dto de inscrições
  backend/src/main/java/com/senac/gestaocurso/dto/InscricaoDto.java
Labels: bug

#44 fix: corrigindo strategy aula service
  backend/src/main/java/com/senac/gestaocurso/service/AulaService.java
Labels: bug

#45 Fixing inscricoes
  backend/src/main/java/com/senac/gestaocurso/dto/CursoDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/InscricaoDto.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Curso.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Inscricao.java
Labels: enhancement, refactor

#46 Notfound to nocontent
  backend/src/main/java/com/senac/gestaocurso/enterprise/exception/NotFoundException.java
  backend/src/main/java/com/senac/gestaocurso/enterprise/exception/OkNoContent.java
  backend/src/main/java/com/senac/gestaocurso/resource/AbstractController.java
  backend/src/main/java/com/senac/gestaocurso/service/AulaService.java
  backend/src/main/java/com/senac/gestaocurso/service/CargoService.java
  backend/src/main/java/com/senac/gestaocurso/service/CertificacaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/CursoService.java
  backend/src/main/java/com/senac/gestaocurso/service/DadosBancarioService.java
  backend/src/main/java/com/senac/gestaocurso/service/DependenteService.java
  backend/src/main/java/com/senac/gestaocurso/service/ExperienciaAnteriorService.java
  backend/src/main/java/com/senac/gestaocurso/service/FiliacaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/FrequenciaService.java
  backend/src/main/java/com/senac/gestaocurso/service/FuncionarioService.java
  backend/src/main/java/com/senac/gestaocurso/service/InscricaoService.java
  backend/src/main/java/com/senac/gestaocurso/service/MateriaService.java
Labels: refactor

#47 refactor: DTOs de Curso & Materia
  backend/src/main/java/com/senac/gestaocurso/dto/CursoDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/MateriaDto.java
Labels: bug

#49 fix:dtos upd e jsonignore
  backend/src/main/java/com/senac/gestaocurso/dto/AulaDto.java
  backend/src/main/java/com/senac/gestaocurso/dto/CursoDto.java
  backend/src/main/java/com/senac/gestaocurso/models/domain/Curso.java
Labels: bug
